<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Addition" targetNamespace="http://www.example.org/Addition/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/Addition/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="AdditionSOAP" originalBindingStyle="document"/>
        <generatedXSD location="Addition_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/Addition/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="Addition_InlineSchema1.xsd"/>
</xsd:schema>
    </wsdl:types>
  <wsdl:message name="AdditionRequest">
    <wsdl:part element="tns:Addition" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="AdditionResponse">
    <wsdl:part element="tns:AdditionResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Addition">
    <wsdl:operation name="Addition">
      <wsdl:input message="tns:AdditionRequest"/>
      <wsdl:output message="tns:AdditionResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AdditionSOAP" type="tns:Addition">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Addition">
      <soap:operation soapAction="http://www.example.org/Addition/Addition"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Addition">
    <wsdl:port binding="tns:AdditionSOAP" name="AdditionSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>